### PR TITLE
#157801290 Integrate coveralls

### PR DESCRIPTION
**Pull request by Rhotimee**
#### What does this PR do?
Integrate Coveralls on the andela/asgard-cfh repository

#### Description of Task to be completed?
Integrated Coveralls by adding .coveralls.yml file on the repository and activated the repository on the Coveralls website.
Added coveralls markdown on the README.md file.

#### How should this be manually tested?
Coveralls badge should be seen on the README.

#### Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?
#157801290

### CODE REVIEW

**Review by fortunee — COMMENTED** [review]
I'm sure you're not done with this 😄  @Rhotimee

**Comment by fortunee** [comment]
The coverage badge on the README is still `unknown` please fix it ASAP. Thanks @Rhotimee

**Comment by Rhotimee** [comment]
@fortunee  It seems coveralls takes time to display. Everything looks good to me.

**Review by fortunee — APPROVED** [review]
Good job @Rhotimee.

**Pull request merged**
